#!/bin/sh

if [[ $1 == upgrade ]]; then
	/bin/launchctl unload /Library/LaunchDaemons/com.luobin.LUAScriptDaemon.LUAScriptDaemon.plist
fi

chown root:wheel /usr/bin/LUAScriptDaemon
chmod 755 /usr/bin/LUAScriptDaemon
chown root:wheel /Library/LaunchDaemons/com.luobin.LUAScriptDaemon.LUAScriptDaemon.plist
chmod 644 /Library/LaunchDaemons/com.luobin.LUAScriptDaemon.LUAScriptDaemon.plist

/bin/launchctl load /Library/LaunchDaemons/com.luobin.LUAScriptDaemon.LUAScriptDaemon.plist

exit 0
