#!/bin/sh

# This script is executed AFTER the Debian package is INSTALLED
# For information about this file, see http://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html#s-maintscripts.

cd "/Applications/LUAScriptElfUI.app/"

# process origin binary
mv LUAScriptElfUI LUAScriptElfUI_
chown root.wheel LUAScriptElfUI_
chmod +s 		 LUAScriptElfUI_

cont=`cat <<"EOF"
#!/bin/bash
dir=$(dirname "$0")
exec "${dir}"/LUAScriptElfUI_ "$@"
EOF
`
# create new fake binary
echo -e "$cont" > LUAScriptElfUI
chown root.wheel  LUAScriptElfUI
chmod +x 		  LUAScriptElfUI